apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sl-project-ingress
  namespace: blogging-system
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: sl-project.apps.168.107.11.85.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blog-service
                port:
                  number: 80
          - path: /subscribe
            pathType: Prefix
            backend:
              service:
                name: subscriber-service
                port:
                  number: 80
