apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ls-blogging-system

resources:
  - ls-namespace.yaml
  - ls-postgres-statefulset.yaml
  - ls-postgres-service.yaml
  - ls-blog-deployment.yaml
  - ls-blog-service.yaml
  - ls-subscriber-deployment.yaml
  - ls-subscriber-service.yaml
  # - ls-notifier-deployment.yaml
  - ls-ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: ls-project

# ✅ HTML 파일들을 ConfigMap으로 생성
configMapGenerator:
  - name: ls-project-blog-html
    files:
      - html/ls-index.html
      - html/ls-subscribe.html

generatorOptions:
  disableNameSuffixHash: true
