apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-blog-service
  namespace: ls-blogging-system
  labels:
    app: ls-blog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ls-blog-service
  template:
    metadata:
      labels:
        app: ls-blog-service
    spec:
      containers:
        - name: ls-blog-service
          image: nginx:1.27-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

          # ✅ 여기서부터 중요 (HTML 마운트)
          volumeMounts:
            - name: blog-html
              mountPath: /usr/share/nginx/html     # ✅ nginx 기본 루트
              readOnly: true

      volumes:
        - name: blog-html
          configMap:
            name: ls-project-blog-html    # ✅ kustomize에서 만든 ConfigMap 이름
