apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-blog-service
  namespace: ls-blogging-system
  labels:
    app: blog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ls-blog-service
  template:
    metadata:
      labels:
        app: ls-blog-service
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: ls-blog-html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: ls-blog-html
          configMap:
            name: ls-project-blog-html   # kustomize로 생성한 ConfigMap 이름
