apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-subscriber-service          # 또는 subscribe-service
  namespace: ls-blogging-system
  labels:
    app: ls-subscriber-service         # 위 name과 맞춰주기
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ls-subscriber-service
  template:
    metadata:
      labels:
        app: ls-subscriber-service
    spec:
      containers:
        - name: ls-subscriber-service
          image: nginx:1.27-alpine          # ✅ nginx 이미지로 교체
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80             # ✅ nginx 기본 포트
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
