apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog-app

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: blog-board
  managed-by: argocd

images:
  - name: blog-board-app
    newName: nginx
    newTag: alpine
