apiVersion: v1
kind: Service
metadata:
  name: blog-board-service
spec:
  type: ClusterIP
  selector:
    app: blog-board
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
