apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blogging-system

resources:
  - namespace.yaml

  # DB 관련
  # - db-secret.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml

  # 앱 관련
  - blog-deployment.yaml
  - blog-service.yaml
  - subscriber-deployment.yaml
  - subscriber-service.yaml
  - notifier-deployment.yaml
  - ingress.yaml
  - notifier-service.yaml

commonLabels:
  app.kubernetes.io/part-of: sl-project
