apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 이 네임스페이스 안에 전부 배포
namespace: blogging-system

resources:
  - namespace.yaml
  - blog-deployment.yaml
  - blog-service.yaml
  - subscriber-deployment.yaml
  - subscriber-service.yaml
  - notifier-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: blog-email-system
