apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-board-ingress
spec:
  rules:
  - host: dev.blog.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blog-board-service
            port:
              number: 80
