# argocd-blog-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-blog-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # 필요하면 나중에 rewrite 추가 가능
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: apps.168.107.11.85.nip.io   # 원하는 도메인으로 변경 가능
      http:
        paths:
          - path: /argocd
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80

          - path: /blog
            pathType: Prefix
            backend:
              service:
                name: blog-nginx
                port:
                  number: 80
