apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog-app-prod

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: prod

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml

configMapGenerator:
  - name: nginx-config
    files:
      - nginx.conf
  - name: html-content
    files:
      - index.html
      - board.html
      - blog.html
      - post.html
      - styles.css
      - script.js

replicas:
  - name: blog-board-app
    count: 3
