configs:
  params:
    server.insecure: true
    server.basehref: /argocd
    server.rootpath: /argocd

global:
  domain: apps.168.107.11.85.nip.io

server:
  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: apps.168.107.11.85.nip.io

    path: /argocd
    pathType: Prefix

    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

    # TLS 필요 없으면 extraTls 블록은 빼도 됨
    # extraTls:
    #   - hosts:
    #       - apps.168.107.11.85.nip.io
    #     secretName: argocd-tls
