apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-metrics-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: apps.168.107.11.85.nip.io
      http:
        paths:
          # /prometheus, /prometheus/, /prometheus/graph â†’ /, /graph
          # /alertmanager, /alertmanager/, /alertmanager/#/alerts â†’ /, /#/alerts
          - path: /alertmanager(/|$)(.*)
            pathType: ImplementationSpecific      # ðŸ”´ ì—¬ê¸°!
            backend:
              service:
                name: prometheus-kube-prometheus-alertmanager     # ì‹¤ì œ Alertmanager ì„œë¹„ìŠ¤
                port:
                  number: 9093                      # ì„œë¹„ìŠ¤ port
