apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    argocd.argoproj.io/tracking-id: unified-ingress:kustomize.config.k8s.io/Kustomization:ingress-nginx/

resources:
  - ingress-controller-svc.yaml
  - argocd-ingress.yaml
  - nginx-ingress.yaml
  - blog-ingress.yaml
  - nginx-svc-patch.yaml
